### ISSUE TITLE
请问在用K-BERT做NER任务时为何舍弃了CRF层？是因为K-BERT多分类结果就已经足够很好了吗？

### ISSUE THREAD

**Issue by Finley1991** [autoliuweijie/K-BERT#10]

**Comment by autoliuweijie** [comment]
对于BERT/K-BERT，对于此类较深的模型，我们发现其隐藏层之间的状态就可以学会到Tag之间的转移概率。在实验中，我们发现仅用Softmax就能达到和CRF一样的效果，且效率更高。CRF对每个Token无法并行处理，且不易放入GPU中。
