### ISSUE TITLE
 请问有其他方式可以下载google_model.bin和CnDbpedia.spo

### ISSUE THREAD

**Issue by WenTingTseng** [autoliuweijie/K-BERT#14]
你好 想請問 是否能
其他方式可以下载google_model.bin和CnDbpedia.spo方式，我沒有QQ帳號也一直辦不成功
或是能否直接Email至:d0409857@gmail.com信箱，
Thanks for your help

**Comment by autoliuweijie** [comment]
> 你好 想請問 是否能
> 其他方式可以下载google_model.bin和CnDbpedia.spo方式，我沒有QQ帳號也一直辦不成功
> 或是能否直接Email至:[d0409857@gmail.com](mailto:d0409857@gmail.com)信箱，
> Thanks for your help

你好，非常抱歉，由于google_model.bin和CnDbpedia.spo文件较大，无法通过邮件方式发送。目前我们只有腾讯云盘的下载方式，除了使用QQ号，也可以尝试使用微信下载。

**Comment by WenTingTseng** [comment]
OK，感謝提醒，已用微信下載成功
謝謝
