### ISSUE TITLE
How can I use my own knowledge graph

### ISSUE THREAD

**Issue by alokpadhi** [autoliuweijie/K-BERT#19]
Any way to build a custom knowledge graph from a corpus of data and use that for training a multi-label classification?

**Comment by alokpadhi** [comment]
I solved it. Using textacy we can generate the SPO format and then simply write into the .spo file worked.

**Comment by WenTingTseng** [comment]
Can you elaborate on how to use textacy to generate the SPO format and then simply write into the .spo file worked.
Thanks a lot for your help

**Comment by phc4valid** [comment]
Hi @alokpadhi , I'm also trying to build a knowledge graph and train on a multi-label classification task in the domain of health care.  Is there any chance having the opportunity to discuss with you and have a look on the work ? Really want to implement it on a chinese data. I also want to change the pretrained LM to a higher performance one (etc:RoBERTa  ...) combining with the knowledge graph mentioned in the article. Any suggestions ?  Thanks for your timing reading and please stay safe ,looking forward to your voice, thanks alot.
