### ISSUE TITLE
这篇论文的思路非常新颖，且具备独创性，但结果似乎差强人意

### ISSUE THREAD

**Issue by lexmen318** [autoliuweijie/K-BERT#2]
从论文的实现思路来看，应该还是比较清晰的。

但从实验结果来看，似乎在特定领域上相比BERT的性能提升幅度不明显，不知道是否深入分析过原因？

感谢！

**Comment by autoliuweijie** [comment]
确实，我们发现K-BERT在很多任务上相比BERT的提升甚至不如超参的影响，我们也在分析其中的原因，可能原因有：

1. 目前用于测评的任务并非是“知识驱动”的任务，这些数据在标注时并不需要背景知识，引入知识反而被认为标注“错误”；
2. 知识图谱的质量不高，目前我们的知识图谱大多从开发领域图谱中筛选的，其中的知识BERT通过大规模语料预训练也能得到。

不得不承认，K-BERT还是存在很多问题，我们还在进一步优化和改进，谢谢您的关注。

**Comment by autoliuweijie** [comment]
确实，我们发现K-BERT在很多任务上效果不显著，我们也在分析其中的原因，可能原因有：

1. 目前用于测评的任务并非是“知识驱动”的任务，这些数据在标注时并不需要背景知识，引入知识反而被认为标注“错误”；
2. 知识图谱的质量不高，目前我们的知识图谱大多从开发领域图谱中筛选的，其中的知识BERT通过大规模语料预训练也能得到。

不得不承认，K-BERT还是存在很多问题，我们还在进一步优化和改进，谢谢您的关注。

**Comment by lexmen318** [comment]
Github很奇怪，这问题记得之前已经关闭了。感觉好像穿越了！
