### ISSUE TITLE
 关于knowledge Graph data 自动产生

### ISSUE THREAD

**Issue by WenTingTseng** [autoliuweijie/K-BERT#26]
作者你好我想请问关于像是HowNet.spo这种资料如果在我的任务上没有相关资料是否有办法自动产生呢?
像这种Entity Relation Entity自动产生的方法作者有没有参考过相关的论文或作法呢

谢谢

**Comment by autoliuweijie** [comment]
> 作者你好我想请问关于像是HowNet.spo这种资料如果在我的任务上没有相关资料是否有办法自动产生呢?
> 像这种Entity Relation Entity自动产生的方法作者有没有参考过相关的论文或作法呢
> 
> 谢谢

知识图谱（spo文件）的生成是一个很费时费力的工作，目前高质量的知识图谱都是人工提取的。
自动生成的话可以看一些实体关系抽取的论文，可关注清华的OpenNRE工具：
https://github.com/thunlp/OpenNRE

**Comment by WenTingTseng** [comment]
谢谢您的建议
不过OpenNRE只能用在英文的语料库上?
