### ISSUE TITLE
Figure 1下注释问题

### ISSUE THREAD

**Issue by STHSF** [autoliuweijie/K-BERT#28]
![image](https://user-images.githubusercontent.com/8037442/79452202-557d4700-801a-11ea-9939-5af2b4dbdf0e.png)

请问, 这里的RL models是LR models吧, 我在文中没找到RL的全称.

**Comment by autoliuweijie** [comment]
> ![image](https://user-images.githubusercontent.com/8037442/79452202-557d4700-801a-11ea-9939-5af2b4dbdf0e.png)
> 
> 请问, 这里的RL models是LR models吧, 我在文中没找到RL的全称.

感谢您指出这个问题，确实是拼写错误，应该是LR，即Language Representation
