### ISSUE TITLE
K-BERT在阅读理解任务

### ISSUE THREAD

**Issue by WenTingTseng** [autoliuweijie/K-BERT#29]
您好
我想请问K-BERT是否也能应用在阅读理解上的任务(像是SQuAD资料集)

谢谢

**Comment by autoliuweijie** [comment]
> 您好
> 我想请问K-BERT是否也能应用在阅读理解上的任务(像是SQuAD资料集)
> 
> 谢谢

理论上是可以的，BERT所支持的任务都可以直接切换到K-BERT。

**Comment by WenTingTseng** [comment]
好的 謝謝
