### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by dogydev** [autoliuweijie/K-BERT#3]
Is there an approximate date that the code will be released on?

**Comment by dogydev** [comment]
Thanks in advance.

**Comment by autoliuweijie** [comment]
> Is there an approximate date that the code will be released on?

Thanks for your attention. Good news. This paper has been accepted for publication on AAAI2020 (February 7, 2020). Currently, I'm sorting out the source code and will be released before the conference.

**Comment by autoliuweijie** [comment]
We have released our source code.

**Comment by dogydev** [comment]
Thanks!
