### ISSUE TITLE
单独BERT效果

### ISSUE THREAD

**Issue by WenTingTseng** [autoliuweijie/K-BERT#34]
你好
我想请问 是否可以只看BERT不加Knowledge graph的效果
程式上参数如何设定

谢谢

**Comment by autoliuweijie** [comment]
> 你好
> 我想请问 是否可以只看BERT不加Knowledge graph的效果
> 程式上参数如何设定
> 
> 谢谢

你可以创建一个空的none.spo文件，然后--kg none.spo就相当于普通的BERT了。

**Comment by WenTingTseng** [comment]
好的 谢谢
不过我在我的dataset实验好像没加knowledge Graph效果还会比较好，这个问题是出在哪?knowledge Graph我是针对我本身资料所建立的

**Comment by autoliuweijie** [comment]
> 好的 谢谢
> 不过我在我的dataset实验好像没加knowledge Graph效果还会比较好，这个问题是出在哪?knowledge Graph我是针对我本身资料所建立的

你的KG质量如何？ 以及你们的dataset是否确实需要知识？

经过我们的实验，我们发现KG只有对于专业领域任务比较有效，且KG中需要保护专业知识三元组，而非常识三元组。
