### ISSUE TITLE
消融实验相关问题

### ISSUE THREAD

**Issue by Graduo** [autoliuweijie/K-BERT#36]
您好，我就着您的框架做了一些实验，效果都很不错。不过对知识所起的作用有一些不同理解，我做的实验结果显示并非有助于句子理解的知识起到的作用效果更好，因此我对kbert的起作用的机制有一些其他推测，您如果有兴趣可以详细探讨一下。想问您有相关消融实验数据么，软位置，可见矩阵等哪个机制起到了作用呢。谢谢

**Comment by autoliuweijie** [comment]
> 您好，我就着您的框架做了一些实验，效果都很不错。不过对知识所起的作用有一些不同理解，我做的实验结果显示并非有助于句子理解的知识起到的作用效果更好，因此我对kbert的起作用的机制有一些其他推测，您如果有兴趣可以详细探讨一下。想问您有相关消融实验数据么，软位置，可见矩阵等哪个机制起到了作用呢。谢谢

你好，消融可展示的数据已在论文中展示，中间数据并没有留存。 我们在论文中展示两个不同任务的消融实验结果，因为我们发现任务不同，消融实验结论也不同。对于NER类的任务，软位置和可见矩阵共同起作用，而对于QA类任务，似乎软位置并无太多作用。另外，我们还猜测这与知识图谱的质量和类型有关。

以上是我们的理解和推测，不一定是正确的。

如果您有进一步的实验结果和推测，欢迎提出来一起讨论讨论哈。

**Comment by Graduo** [comment]
好的，方便留一下您邮箱地址么，或者怎样联系到您，我将我的一些结论和您探讨一下

**Comment by autoliuweijie** [comment]
> 好的，方便留一下您邮箱地址么，或者怎样联系到您，我将我的一些结论和您探讨一下

我的邮箱是dataliu@pku.edu.cn哈。
