### ISSUE TITLE
Ask for help about your article

### ISSUE THREAD

**Issue by ColaXww** [autoliuweijie/K-BERT#4]
Dear Dr.Liu:        
        I am a master's student at ISCAS, My research is focused on EMR information extraction. I have recently read your paper "K-BERT: Enabling Language Representation with Knowledge Graph" and got a lot of inspiration from it, thank you!
       I am wondering if you could kindly send me the slides for presentation or other materials about it. I promise they will be used only for research purposed.
        My email：wenwen2019@iscas.ac.cn
        Yours sincerely,
        Wenwen Xu

**Comment by autoliuweijie** [comment]
Thank you for your attention. 
This paper is accepted as a poster presentation at AAAI-20, the poster has not completed. 
All the materials about K-BERT have been released on the Github, including knowledge graphs and datasets

**Comment by ColaXww** [comment]
ok,thanks!

> Thank you for your attention.
> This paper is accepted as a poster presentation at AAAI-20, the poster has not completed.
> All the materials about K-BERT have been released on the Github, including knowledge graphs and datasets

OK，thank you！

**Comment by ColaXww** [comment]
> Thank you for your attention.
> This paper is accepted as a poster presentation at AAAI-20, the poster has not completed.
> All the materials about K-BERT have been released on the Github, including knowledge graphs and datasets

ok, thank you!
