### ISSUE TITLE
QA Model?

### ISSUE THREAD

**Issue by dogydev** [autoliuweijie/K-BERT#5]
WIll Question Answering code be released? If so, when?

**Comment by dogydev** [comment]
Thanks in advance

**Comment by autoliuweijie** [comment]
> WIll Question Answering code be released? If so, when?

In BERT/K-BERT，Question Answering is taken as a sentences-pair classification, i.e., whether sentence B is the answer to sentence A. 

You can download QA datasets from [here](https://share.weiyun.com/5Id9PVZ), and use ``run_kbert_cls.py`` for sentences-pair classification.

**Comment by dogydev** [comment]
Thank you :)

**Comment by yuweijiang** [comment]
@autoliuweijie  I can not see the dataset of NLPCC-DBQA.
