### ISSUE TITLE
About the contents of spo 

### ISSUE THREAD

**Issue by isspek** [autoliuweijie/K-BERT#61]
Dear @autoliuweijie,

thank you so much for your study. I would like to experiment K-BERT for a custom graphs. However, I need to convert to spo format. I checked the examples, which are in Chinese. So I couldn't understand the contents and format of spo. I would appreciate it if you could give me an example in English. 

Kind regards
Ipek

**Comment by autoliuweijie** [comment]
Each line is in the format of "subject_name\tpredicate\tobject_name\n", where "\t" is the tab tag.

**Comment by isspek** [comment]
Thanks @autoliuweijie.
