### ISSUE TITLE
情感分析预测出来的结果都是1

### ISSUE THREAD

**Issue by AlanLinZhizhou** [autoliuweijie/K-BERT#63]
我把数据集换成了Moview Review（英文数据集，bert对应的.bin以及词典等也换成了英文），正负样本1：1，但是在训练的时候模型只猜测结果1。
对于好多英文数据集都是这种情况，只有少数几个数据集才能正常出结果，想问一下作者有遇见这种情况么，这个可能是什么原因呢？
![image](https://user-images.githubusercontent.com/35172569/120155373-532c7b00-c223-11eb-880d-0392045516a4.png)

**Comment by kxy-cheng** [comment]
这个问题我也遇到了。我把基础模型更换了之后所有预测都变成1了。输出的logits要么差别很小要么一模一样。不知道这个问题您现在解决了吗
