### ISSUE TITLE
关于您给的google_models.bin

### ISSUE THREAD

**Issue by ucascola** [autoliuweijie/K-BERT#8]
请问您给的下载链接中的google_models.bin预训练模型，是您自己训练的，还是谷歌官方的版本呢？
万分感谢！

**Comment by autoliuweijie** [comment]
> 请问您给的下载链接中的google_models.bin预训练模型，是您自己训练的，还是谷歌官方的版本呢？
> 万分感谢！

是Google官方版本训练的，然后转换成本项目可用的格式。

**Comment by ucascola** [comment]
> > 请问您给的下载链接中的google_models.bin预训练模型，是您自己训练的，还是谷歌官方的版本呢？
> > 万分感谢！
> 
> 是Google官方版本训练的，然后转换成本项目可用的格式。

嗯嗯 好的 谢谢您！
