### ISSUE TITLE
Where is the NLPCC-DBQA?

### ISSUE THREAD

**Issue by yuweijiang** [autoliuweijie/K-BERT#9]
Hi, I am interested in this paper, while I can not find the NLPCC-DBQA dataset from your source codes. Could you show the results of the NLPCC-DBQA from your codes? Thanks.

**Comment by autoliuweijie** [comment]
Sorry, I forget to upload the NLPCC-DBQA dataset. I have fixed this problem. Then, you can download it from [here](https://share.weiyun.com/5Id9PVZ), which is named as "nlpcc-dbqa".

You can test K-BERT with ``run_kbert_cls.py``.
